export const userlist = [
    {
        "id": 1,
        "firstName": "Kyle",
        "lastName": "Henry",
        "email": "Kyle.Henry@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-12-01T12:06:04.777Z"
    },
    {
        "id": 2,
        "firstName": "Janie",
        "lastName": "Bush",
        "email": "Janie.Bush@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-06-11T20:00:18.376Z"
    },
    {
        "id": 3,
        "firstName": "Eugene",
        "lastName": "Poole",
        "email": "Eugene.Poole@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": true,
        "lastLogin": "2018-10-31T11:21:36.184Z"
    },
    {
        "id": 4,
        "firstName": "Austin",
        "lastName": "Leonard",
        "email": "Austin.Leonard@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-03-30T17:19:13.718Z"
    },
    {
        "id": 5,
        "firstName": "Mathilda",
        "lastName": "Strickland",
        "email": "Mathilda.Strickland@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-03-05T11:30:18.663Z"
    },
    {
        "id": 6,
        "firstName": "Jose",
        "lastName": "Munoz",
        "email": "Jose.Munoz@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-07-16T19:49:22.425Z"
    },
    {
        "id": 7,
        "firstName": "Carolyn",
        "lastName": "Huff",
        "email": "Carolyn.Huff@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-05-25T00:59:10.532Z"
    },
    {
        "id": 8,
        "firstName": "Jayden",
        "lastName": "Cannon",
        "email": "Jayden.Cannon@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-09-14T10:37:24.935Z"
    },
    {
        "id": 9,
        "firstName": "Bradley",
        "lastName": "Jenkins",
        "email": "Bradley.Jenkins@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-12-01T17:22:41.518Z"
    },
    {
        "id": 10,
        "firstName": "Clara",
        "lastName": "McLaughlin",
        "email": "Clara.McLaughlin@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-07-11T17:51:03.658Z"
    },
    {
        "id": 11,
        "firstName": "Nellie",
        "lastName": "Gill",
        "email": "Nellie.Gill@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": true,
        "lastLogin": "2018-08-31T17:07:59.475Z"
    },
    {
        "id": 12,
        "firstName": "Victoria",
        "lastName": "Collins",
        "email": "Victoria.Collins@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-02-21T15:08:07.376Z"
    },
    {
        "id": 13,
        "firstName": "Blake",
        "lastName": "Reed",
        "email": "Blake.Reed@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-11-03T10:43:13.033Z"
    },
    {
        "id": 14,
        "firstName": "Jimmy",
        "lastName": "Miller",
        "email": "Jimmy.Miller@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-02-20T11:21:50.042Z"
    },
    {
        "id": 15,
        "firstName": "Bertha",
        "lastName": "King",
        "email": "Bertha.King@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-04-13T15:26:05.790Z"
    },
    {
        "id": 16,
        "firstName": "Jeremy",
        "lastName": "Paul",
        "email": "Jeremy.Paul@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-12-02T01:29:47.016Z"
    },
    {
        "id": 17,
        "firstName": "Larry",
        "lastName": "Cooper",
        "email": "Larry.Cooper@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-11-20T16:09:57.686Z"
    },
    {
        "id": 18,
        "firstName": "Benjamin",
        "lastName": "Harmon",
        "email": "Benjamin.Harmon@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": true,
        "lastLogin": "2018-10-20T18:11:35.234Z"
    },
    {
        "id": 19,
        "firstName": "Nettie",
        "lastName": "Hart",
        "email": "Nettie.Hart@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-07-09T18:12:18.800Z"
    },
    {
        "id": 20,
        "firstName": "Myra",
        "lastName": "Santos",
        "email": "Myra.Santos@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-11-19T18:21:29.785Z"
    },
    {
        "id": 21,
        "firstName": "Caleb",
        "lastName": "Logan",
        "email": "Caleb.Logan@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-02-02T21:04:52.051Z"
    },
    {
        "id": 22,
        "firstName": "Ray",
        "lastName": "Cummings",
        "email": "Ray.Cummings@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-06-30T19:07:16.472Z"
    },
    {
        "id": 23,
        "firstName": "Nicholas",
        "lastName": "Haynes",
        "email": "Nicholas.Haynes@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-07-30T23:37:21.918Z"
    },
    {
        "id": 24,
        "firstName": "Gregory",
        "lastName": "Schwartz",
        "email": "Gregory.Schwartz@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-05-10T02:11:17.568Z"
    },
    {
        "id": 25,
        "firstName": "Norman",
        "lastName": "Daniel",
        "email": "Norman.Daniel@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-08-27T04:50:35.623Z"
    },
    {
        "id": 26,
        "firstName": "Christine",
        "lastName": "Bishop",
        "email": "Christine.Bishop@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-111-05T22:20:44.702Z"
    },
    {
        "id": 27,
        "firstName": "Lou",
        "lastName": "Butler",
        "email": "Lou.Butler@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": true,
        "lastLogin": "2018-05-25T12:52:39.201Z"
    },
    {
        "id": 28,
        "firstName": "Della",
        "lastName": "Ryan",
        "email": "Della.Ryan@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-11-19T21:42:08.543Z"
    },
    {
        "id": 29,
        "firstName": "Johnny",
        "lastName": "Cummings",
        "email": "Johnny.Cummings@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-06-27T05:46:30.483Z"
    },
    {
        "id": 30,
        "firstName": "Johnny",
        "lastName": "Dean",
        "email": "Johnny.Dean@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-06-11T20:18:21.794Z"
    },
    {
        "id": 31,
        "firstName": "Rebecca",
        "lastName": "Hayes",
        "email": "Rebecca.Hayes@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-04-28T08:20:51.735Z"
    },
    {
        "id": 32,
        "firstName": "Mildred",
        "lastName": "Luna",
        "email": "Mildred.Luna@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-12-02T16:44:32.170Z"
    },
    {
        "id": 33,
        "firstName": "Alberta",
        "lastName": "Owen",
        "email": "Alberta.Owen@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-09-14T09:53:29.466Z"
    },
    {
        "id": 34,
        "firstName": "May",
        "lastName": "Weber",
        "email": "May.Weber@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-11-11T00:42:37.635Z"
    },
    {
        "id": 35,
        "firstName": "Norman",
        "lastName": "Paul",
        "email": "Norman.Paul@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-06-22T00:14:18.588Z"
    },
    {
        "id": 36,
        "firstName": "Annie",
        "lastName": "Welch",
        "email": "Annie.Welch@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-04-01T13:18:46.470Z"
    },
    {
        "id": 37,
        "firstName": "Francis",
        "lastName": "Baldwin",
        "email": "Francis.Baldwin@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-10-11T22:49:02.337Z"
    },
    {
        "id": 38,
        "firstName": "Dennis",
        "lastName": "Stephens",
        "email": "Dennis.Stephens@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-04-14T03:07:24.040Z"
    },
    {
        "id": 39,
        "firstName": "Christopher",
        "lastName": "McLaughlin",
        "email": "Christopher.McLaughlin@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-11-07T03:48:49.209Z"
    },
    {
        "id": 40,
        "firstName": "Lina",
        "lastName": "Wells",
        "email": "Lina.Wells@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-05-20T23:27:44.769Z"
    },
    {
        "id": 41,
        "firstName": "Hilda",
        "lastName": "Byrd",
        "email": "Hilda.Byrd@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-05-10T06:30:49.203Z"
    },
    {
        "id": 42,
        "firstName": "Joe",
        "lastName": "Fowler",
        "email": "Joe.Fowler@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-06-04T18:09:52.467Z"
    },
    {
        "id": 43,
        "firstName": "Nora",
        "lastName": "Robertson",
        "email": "Nora.Robertson@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-11-18T09:38:35.502Z"
    },
    {
        "id": 44,
        "firstName": "Billy",
        "lastName": "Craig",
        "email": "Billy.Craig@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-03-05T08:40:56.292Z"
    },
    {
        "id": 45,
        "firstName": "Maria",
        "lastName": "Williamson",
        "email": "Maria.Williamson@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-03-14T18:05:59.530Z"
    },
    {
        "id": 46,
        "firstName": "Harvey",
        "lastName": "Baldwin",
        "email": "Harvey.Baldwin@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-03-12T05:52:09.516Z"
    },
    {
        "id": 47,
        "firstName": "Emilie",
        "lastName": "Simpson",
        "email": "Emilie.Simpson@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-04-17T20:14:34.290Z"
    },
    {
        "id": 48,
        "firstName": "Andrew",
        "lastName": "Holloway",
        "email": "Andrew.Holloway@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-02-03T19:29:43.697Z"
    },
    {
        "id": 49,
        "firstName": "Leona",
        "lastName": "Mendoza",
        "email": "Leona.Mendoza@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-02-23T22:28:11.645Z"
    },
    {
        "id": 50,
        "firstName": "Frank",
        "lastName": "Hoffman",
        "email": "Frank.Hoffman@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-05-15T07:59:15.282Z"
    },
    {
        "id": 51,
        "firstName": "John",
        "lastName": "Berry",
        "email": "John.Berry@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-05-27T06:35:24.468Z"
    },
    {
        "id": 52,
        "firstName": "Joe",
        "lastName": "Duncan",
        "email": "Joe.Duncan@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": true,
        "lastLogin": "2018-05-13T11:18:40.408Z"
    },
    {
        "id": 53,
        "firstName": "Francis",
        "lastName": "Morrison",
        "email": "Francis.Morrison@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-06-20T12:28:38.245Z"
    },
    {
        "id": 54,
        "firstName": "Claudia",
        "lastName": "Elliott",
        "email": "Claudia.Elliott@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-10-15T10:40:12.654Z"
    },
    {
        "id": 55,
        "firstName": "Cora",
        "lastName": "Patterson",
        "email": "Cora.Patterson@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-08-29T12:21:21.077Z"
    },
    {
        "id": 56,
        "firstName": "Nathan",
        "lastName": "Ball",
        "email": "Nathan.Ball@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-05-09T02:34:28.411Z"
    },
    {
        "id": 57,
        "firstName": "Duane",
        "lastName": "Sparks",
        "email": "Duane.Sparks@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-09-17T23:03:00.053Z"
    },
    {
        "id": 58,
        "firstName": "Ricky",
        "lastName": "Paul",
        "email": "Ricky.Paul@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-10-25T19:14:31.240Z"
    },
    {
        "id": 59,
        "firstName": "Lily",
        "lastName": "Riley",
        "email": "Lily.Riley@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-02-04T02:26:08.881Z"
    },
    {
        "id": 60,
        "firstName": "Antonio",
        "lastName": "Hodges",
        "email": "Antonio.Hodges@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-04-17T23:52:13.867Z"
    },
    {
        "id": 61,
        "firstName": "Jayden",
        "lastName": "Duncan",
        "email": "Jayden.Duncan@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-05-06T22:37:40.463Z"
    },
    {
        "id": 62,
        "firstName": "Bryan",
        "lastName": "Reeves",
        "email": "Bryan.Reeves@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-08-18T14:58:48.694Z"
    },
    {
        "id": 63,
        "firstName": "Adele",
        "lastName": "Anderson",
        "email": "Adele.Anderson@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-07-29T08:34:59.390Z"
    },
    {
        "id": 64,
        "firstName": "Nathaniel",
        "lastName": "Pierce",
        "email": "Nathaniel.Pierce@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-07-06T17:13:35.431Z"
    },
    {
        "id": 65,
        "firstName": "Melvin",
        "lastName": "Lucas",
        "email": "Melvin.Lucas@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": true,
        "lastLogin": "2018-02-11T07:13:42.971Z"
    },
    {
        "id": 66,
        "firstName": "Katherine",
        "lastName": "Green",
        "email": "Katherine.Green@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-09-15T07:51:28.716Z"
    },
    {
        "id": 67,
        "firstName": "Dominic",
        "lastName": "Edwards",
        "email": "Dominic.Edwards@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-09-20T04:47:44.677Z"
    },
    {
        "id": 68,
        "firstName": "Thomas",
        "lastName": "Barnes",
        "email": "Thomas.Barnes@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-03-06T19:51:37.998Z"
    },
    {
        "id": 69,
        "firstName": "Larry",
        "lastName": "Oliver",
        "email": "Larry.Oliver@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-11-22T21:35:44.510Z"
    },
    {
        "id": 70,
        "firstName": "Bertie",
        "lastName": "Summers",
        "email": "Bertie.Summers@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-02-08T07:34:17.442Z"
    },
    {
        "id": 71,
        "firstName": "Isabel",
        "lastName": "Scott",
        "email": "Isabel.Scott@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-03-07T17:29:33.225Z"
    },
    {
        "id": 72,
        "firstName": "Harriett",
        "lastName": "Griffith",
        "email": "Harriett.Griffith@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-02-03T06:36:12.479Z"
    },
    {
        "id": 73,
        "firstName": "Sara",
        "lastName": "Austin",
        "email": "Sara.Austin@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-08-28T12:56:03.954Z"
    },
    {
        "id": 74,
        "firstName": "Leah",
        "lastName": "Porter",
        "email": "Leah.Porter@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": true,
        "lastLogin": "2018-02-26T05:47:02.656Z"
    },
    {
        "id": 75,
        "firstName": "Rose",
        "lastName": "Douglas",
        "email": "Rose.Douglas@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-05-03T03:37:55.888Z"
    },
    {
        "id": 76,
        "firstName": "Mina",
        "lastName": "McDaniel",
        "email": "Mina.McDaniel@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-07-13T21:18:07.554Z"
    },
    {
        "id": 77,
        "firstName": "Marion",
        "lastName": "Cruz",
        "email": "Marion.Cruz@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-08-02T03:45:00.620Z"
    },
    {
        "id": 78,
        "firstName": "Bruce",
        "lastName": "Richards",
        "email": "Bruce.Richards@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-09-18T12:08:06.491Z"
    },
    {
        "id": 79,
        "firstName": "Vernon",
        "lastName": "Armstrong",
        "email": "Vernon.Armstrong@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-02-21T00:16:39.443Z"
    },
    {
        "id": 80,
        "firstName": "Lillie",
        "lastName": "Kelley",
        "email": "Lillie.Kelley@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-10-10T12:24:18.212Z"
    },
    {
        "id": 81,
        "firstName": "Rodney",
        "lastName": "Gardner",
        "email": "Rodney.Gardner@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-08-01T21:51:43.202Z"
    },
    {
        "id": 82,
        "firstName": "Don",
        "lastName": "Barnett",
        "email": "Don.Barnett@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-10-01T04:27:09.909Z"
    },
    {
        "id": 83,
        "firstName": "Robert",
        "lastName": "Powers",
        "email": "Robert.Powers@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-02-24T03:47:46.888Z"
    },
    {
        "id": 84,
        "firstName": "Viola",
        "lastName": "Kennedy",
        "email": "Viola.Kennedy@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-11-23T23:27:50.138Z"
    },
    {
        "id": 85,
        "firstName": "Ida",
        "lastName": "Mullins",
        "email": "Ida.Mullins@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-11-30T23:25:42.961Z"
    },
    {
        "id": 86,
        "firstName": "Hester",
        "lastName": "Schwartz",
        "email": "Hester.Schwartz@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-04-06T01:55:19.184Z"
    },
    {
        "id": 87,
        "firstName": "Aiden",
        "lastName": "Scott",
        "email": "Aiden.Scott@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-10-05T19:29:59.950Z"
    },
    {
        "id": 88,
        "firstName": "Barry",
        "lastName": "Hines",
        "email": "Barry.Hines@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-10-13T23:16:47.501Z"
    },
    {
        "id": 89,
        "firstName": "Zachary",
        "lastName": "Porter",
        "email": "Zachary.Porter@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-02-18T11:54:53.653Z"
    },
    {
        "id": 90,
        "firstName": "Michael",
        "lastName": "Murray",
        "email": "Michael.Murray@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-10-23T11:07:16.804Z"
    },
    {
        "id": 91,
        "firstName": "Lelia",
        "lastName": "Carson",
        "email": "Lelia.Carson@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-02-24T09:59:15.637Z"
    },
    {
        "id": 92,
        "firstName": "Justin",
        "lastName": "Salazar",
        "email": "Justin.Salazar@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-11-01T13:37:37.278Z"
    },
    {
        "id": 93,
        "firstName": "Kenneth",
        "lastName": "Cunningham",
        "email": "Kenneth.Cunningham@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-08-23T16:23:56.161Z"
    },
    {
        "id": 94,
        "firstName": "Lou",
        "lastName": "Porter",
        "email": "Lou.Porter@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-09-28T19:34:37.073Z"
    },
    {
        "id": 95,
        "firstName": "Isabelle",
        "lastName": "Carter",
        "email": "Isabelle.Carter@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-02-09T22:15:22.324Z"
    },
    {
        "id": 96,
        "firstName": "Daisy",
        "lastName": "Williams",
        "email": "Daisy.Williams@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": true,
        "lastLogin": "2018-03-04T16:42:33.031Z"
    },
    {
        "id": 97,
        "firstName": "Matilda",
        "lastName": "Powers",
        "email": "Matilda.Powers@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-09-01T19:10:32.615Z"
    },
    {
        "id": 98,
        "firstName": "Isabel",
        "lastName": "Young",
        "email": "Isabel.Young@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-02-01T20:53:51.141Z"
    },
    {
        "id": 99,
        "firstName": "Joshua",
        "lastName": "Bowen",
        "email": "Joshua.Bowen@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-10-27T18:36:12.936Z"
    },
    {
        "id": 100,
        "firstName": "Loretta",
        "lastName": "Riley",
        "email": "Loretta.Riley@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-09-19T13:27:12.669Z"
    },
    {
        "id": 101,
        "firstName": "Kevin",
        "lastName": "Haynes",
        "email": "Kevin.Haynes@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-06-21T19:13:44.138Z"
    },
    {
        "id": 102,
        "firstName": "Eric",
        "lastName": "Potter",
        "email": "Eric.Potter@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": true,
        "lastLogin": "2018-10-04T14:16:05.085Z"
    },
    {
        "id": 103,
        "firstName": "Ryan",
        "lastName": "Mendez",
        "email": "Ryan.Mendez@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-07-08T15:19:40.322Z"
    },
    {
        "id": 104,
        "firstName": "Curtis",
        "lastName": "Carter",
        "email": "Curtis.Carter@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-03-24T10:33:46.348Z"
    },
    {
        "id": 105,
        "firstName": "Beatrice",
        "lastName": "Goodman",
        "email": "Beatrice.Goodman@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-08-20T20:08:03.537Z"
    },
    {
        "id": 106,
        "firstName": "Timothy",
        "lastName": "Farmer",
        "email": "Timothy.Farmer@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-02-13T22:29:00.264Z"
    },
    {
        "id": 107,
        "firstName": "Adam",
        "lastName": "Myers",
        "email": "Adam.Myers@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-05-10T05:25:23.767Z"
    },
    {
        "id": 108,
        "firstName": "Amy",
        "lastName": "Chandler",
        "email": "Amy.Chandler@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-06-01T15:30:42.551Z"
    },
    {
        "id": 109,
        "firstName": "Jesse",
        "lastName": "Walker",
        "email": "Jesse.Walker@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-10-22T05:35:54.970Z"
    },
    {
        "id": 110,
        "firstName": "Roxie",
        "lastName": "Kennedy",
        "email": "Roxie.Kennedy@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-08-19T11:55:24.208Z"
    },
    {
        "id": 111,
        "firstName": "Lucy",
        "lastName": "Woods",
        "email": "Lucy.Woods@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-04-24T05:24:15.578Z"
    },
    {
        "id": 112,
        "firstName": "Lela",
        "lastName": "Pratt",
        "email": "Lela.Pratt@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-09-29T06:51:03.565Z"
    },
    {
        "id": 113,
        "firstName": "Hattie",
        "lastName": "Weber",
        "email": "Hattie.Weber@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-05-30T03:04:16.775Z"
    },
    {
        "id": 114,
        "firstName": "Eugene",
        "lastName": "Bryan",
        "email": "Eugene.Bryan@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-09-13T04:26:43.719Z"
    },
    {
        "id": 115,
        "firstName": "Della",
        "lastName": "May",
        "email": "Della.May@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-05-20T19:54:38.821Z"
    },
    {
        "id": 116,
        "firstName": "Theodore",
        "lastName": "Fitzgerald",
        "email": "Theodore.Fitzgerald@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-03-25T16:39:25.583Z"
    },
    {
        "id": 117,
        "firstName": "Genevieve",
        "lastName": "Hoffman",
        "email": "Genevieve.Hoffman@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": true,
        "lastLogin": "2018-05-20T19:18:05.956Z"
    },
    {
        "id": 118,
        "firstName": "Barry",
        "lastName": "Day",
        "email": "Barry.Day@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-03-29T19:59:46.774Z"
    },
    {
        "id": 119,
        "firstName": "Nellie",
        "lastName": "Riley",
        "email": "Nellie.Riley@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-11-10T02:21:24.585Z"
    },
    {
        "id": 120,
        "firstName": "Sally",
        "lastName": "Payne",
        "email": "Sally.Payne@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-02-03T20:14:08.503Z"
    },
    {
        "id": 121,
        "firstName": "Jay",
        "lastName": "Jacobs",
        "email": "Jay.Jacobs@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-08-29T07:28:22.409Z"
    },
    {
        "id": 122,
        "firstName": "Ronnie",
        "lastName": "Medina",
        "email": "Ronnie.Medina@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-03-07T13:58:15.101Z"
    },
    {
        "id": 123,
        "firstName": "Willie",
        "lastName": "Williams",
        "email": "Willie.Williams@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-08-05T20:06:42.778Z"
    },
    {
        "id": 124,
        "firstName": "Willie",
        "lastName": "Soto",
        "email": "Willie.Soto@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-04-30T08:02:09.133Z"
    },
    {
        "id": 125,
        "firstName": "Gary",
        "lastName": "Davis",
        "email": "Gary.Davis@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-05-23T07:38:44.895Z"
    },
    {
        "id": 126,
        "firstName": "Thomas",
        "lastName": "Tate",
        "email": "Thomas.Tate@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-02-22T15:17:24.349Z"
    },
    {
        "id": 127,
        "firstName": "Jesus",
        "lastName": "Lambert",
        "email": "Jesus.Lambert@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-10-30T10:53:14.990Z"
    },
    {
        "id": 128,
        "firstName": "Ola",
        "lastName": "Walton",
        "email": "Ola.Walton@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-08-28T08:15:02.028Z"
    },
    {
        "id": 129,
        "firstName": "Ricky",
        "lastName": "Brady",
        "email": "Ricky.Brady@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-07-10T10:35:58.177Z"
    },
    {
        "id": 130,
        "firstName": "Ida",
        "lastName": "Flores",
        "email": "Ida.Flores@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": true,
        "lastLogin": "2018-07-17T21:13:47.032Z"
    },
    {
        "id": 131,
        "firstName": "Jose",
        "lastName": "Thomas",
        "email": "Jose.Thomas@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-08-03T08:09:19.365Z"
    },
    {
        "id": 132,
        "firstName": "Rosetta",
        "lastName": "Bowers",
        "email": "Rosetta.Bowers@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-10-25T12:14:53.343Z"
    },
    {
        "id": 133,
        "firstName": "Lilly",
        "lastName": "Parks",
        "email": "Lilly.Parks@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-09-22T10:47:03.485Z"
    },
    {
        "id": 134,
        "firstName": "Lilly",
        "lastName": "Washington",
        "email": "Lilly.Washington@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-06-21T07:13:00.354Z"
    },
    {
        "id": 135,
        "firstName": "Mathilda",
        "lastName": "Olson",
        "email": "Mathilda.Olson@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-02-08T20:45:51.772Z"
    },
    {
        "id": 136,
        "firstName": "Terry",
        "lastName": "Cook",
        "email": "Terry.Cook@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-11-19T14:30:18.949Z"
    },
    {
        "id": 137,
        "firstName": "Terry",
        "lastName": "Burgess",
        "email": "Terry.Burgess@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-02-06T10:01:38.484Z"
    },
    {
        "id": 138,
        "firstName": "Olga",
        "lastName": "Norman",
        "email": "Olga.Norman@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-03-17T18:23:56.549Z"
    },
    {
        "id": 139,
        "firstName": "Ina",
        "lastName": "Hamilton",
        "email": "Ina.Hamilton@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-11-22T02:35:55.164Z"
    },
    {
        "id": 140,
        "firstName": "Bertha",
        "lastName": "Myers",
        "email": "Bertha.Myers@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-09-01T17:22:36.911Z"
    },
    {
        "id": 141,
        "firstName": "Inez",
        "lastName": "Hammond",
        "email": "Inez.Hammond@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-08-21T10:31:46.780Z"
    },
    {
        "id": 142,
        "firstName": "Mario",
        "lastName": "Sims",
        "email": "Mario.Sims@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-09-09T05:53:47.980Z"
    },
    {
        "id": 143,
        "firstName": "Frank",
        "lastName": "McCoy",
        "email": "Frank.McCoy@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-10-21T17:13:48.301Z"
    },
    {
        "id": 144,
        "firstName": "Olivia",
        "lastName": "McCormick",
        "email": "Olivia.McCormick@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-10-05T07:49:21.979Z"
    },
    {
        "id": 145,
        "firstName": "Shane",
        "lastName": "Gray",
        "email": "Shane.Gray@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-02-19T05:41:06.936Z"
    },
    {
        "id": 146,
        "firstName": "Miguel",
        "lastName": "Banks",
        "email": "Miguel.Banks@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": true,
        "lastLogin": "2018-11-13T13:53:09.019Z"
    },
    {
        "id": 147,
        "firstName": "Ruth",
        "lastName": "Ballard",
        "email": "Ruth.Ballard@test.com",
        "admin": false,
        "nonAdmin": true,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-06-06T22:34:30.825Z"
    },
    {
        "id": 148,
        "firstName": "Sam",
        "lastName": "Simpson",
        "email": "Sam.Simpson@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-10-26T11:19:46.955Z"
    },
    {
        "id": 149,
        "firstName": "Lena",
        "lastName": "Jimenez",
        "email": "Lena.Jimenez@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": false,
        "archieved": false,
        "lastLogin": "2018-07-06T02:43:05.313Z"
    },
    {
        "id": 150,
        "firstName": "Annie",
        "lastName": "May",
        "email": "Annie.May@test.com",
        "admin": true,
        "nonAdmin": false,
        "favorites": true,
        "archieved": false,
        "lastLogin": "2018-08-20T07:27:40.117Z"
    }
];